In [2]:
from qvm import tensor_gates
from unitary_generator import apply_gate, permutation_arbitrary
from gates import gate_matrix
import numpy as np
from pyquil.quil import Program
from pyquil.gates import *

## Testing

In [3]:
args = (0, 2)
num_qubits = 3
permutation_arbitrary(args, num_qubits)

(<8x8 sparse matrix of type '<type 'numpy.complex128'>'
 	with 8 stored elements in Compressed Sparse Row format>, array([0, 2, 1]), 1)

In [4]:
args = (2, 3, 4, 5, 1, 6, 8)
num_qubits = 12
permutation_arbitrary(args, num_qubits)

(<4096x4096 sparse matrix of type '<type 'numpy.complex128'>'
 	with 4096 stored elements in Compressed Sparse Row format>,
 array([11, 10,  9,  7,  2,  3,  4,  5,  1,  6,  8,  0]),
 1)

In [22]:
print apply_gate(gate_matrix['SWAP'], (0, 2), 3).toarray().astype(np.float64)

[0 2]
[2 1]
[2 1 0]
iterating over indices again...
[1 2 0]
made it
[0 2 1]
1
(0, 2)
[0 2 1]
[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]]


/home/richard-zhu/.local/lib/python2.7/site-packages/ipykernel_launcher.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  """Entry point for launching an IPython kernel.


In [21]:
np.kron(np.eye(2),  gate_matrix['SWAP'])

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

## Development

In [86]:
range(10, 5, -1)

[10, 9, 8, 7, 6]

In [6]:
def swap_inds_helper(i, j, arr):
    tmp = arr[i]
    arr[i] = arr[j]
    arr[j] = tmp
    
def two_swap(j, k, ind_arr):
    """
    """
    new_arr = np.copy(ind_arr)
    if j == k:
        return new_arr
    elif j > k:
        for i in xrange(j, k, -1):
            swap_inds_helper(i - 1, i, new_arr)
    elif j < k:
        for i in xrange(j, k, 1):
            swap_inds_helper(i, i + 1, new_arr)
    return new_arr

In [75]:
num_qubits = 24
k = 24
# inds = np.array([20, 15, 10, 0, 1, 2, 3, 4])
inds = np.random.choice(num_qubits, k, replace=False)

In [82]:
num_qubits = 3
inds = np.array([1, 2])

In [83]:
# First, sort the list and find the median.
sort_i = np.argsort(inds)
sorted_inds = inds[sort_i]
med_i = int(len(sort_i) / 2)
med = sorted_inds[med_i]

# The starting position of all specified Hilbert spaces begins at 
# the qubit at (median - med_i)
start = med - med_i
# Array of final indices the arguments are mapped to, from 
# high index to low index, left to right ordering
final_map = np.arange(start, start + len(inds))[::-1]
start_i = final_map[-1]

print inds 
print final_map
qubit_arr = np.arange(num_qubits)

[1 2]
[2 1]


In [84]:
made_it = False
while made_it == False:
    print "iterating over indices again..."
    for i in range(len(inds)):
        qubit_arr = two_swap(np.where(qubit_arr == inds[i])[0][0], final_map[i], qubit_arr)
        print qubit_arr
        if np.allclose(qubit_arr[final_map[-1]:final_map[0] + 1][::-1], inds):
            print "made it"
            made_it = True
            break


iterating over indices again...
[0 2 1]
made it
