In [12]:
final_map = np.array([2, 0, 1])
print final_map[-2:]
print final_map[-2 +0: -1]

[0 1]
[0]


In [13]:
inds = np.array([0, 2])

# First, sort the list and find the median.
sort_i = np.argsort(inds)
sorted_inds = inds[sort_i]
med_i = int(len(sort_i) / 2)
med = sorted_inds[med_i]

# The starting position of all specified Hilbert spaces begins at 
# the qubit at (median - med_i)
start = med - med_i
# Array of final indices the arguments are mapped to, from 
# high index to low index, left to right ordering
final_map = np.arange(start, start + len(inds))[::-1]
start_i = final_map[-1]

print inds
print final_map

[0 2]
[2 1]


In [14]:
num_qubits = 3
qubit_arr = np.arange(num_qubits)  # current qubit indexing

In [15]:
print permutation_arbitrary((1, 2), 3)[0].toarray()

[1 2]
[2 1]
[2 1 0]
1
[1 2 0]
[1 2 0]
[1 2 0]
[[ 1.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  1.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  1.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  1.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  1.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  1.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  1.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  1.+0.j]]


In [16]:
x = np.array([2, 1])
x[1:3]

array([1])

In [17]:
print apply_gate(gate_matrix['SWAP'], (0, 2), 3).toarray()

[0 2]
[2 1]
[2 1 0]
1
[1 2 0]
0
1
[0 1 2]
1
[1 0 2]


AssertionError: 

In [12]:
final_map = np.arange(10)[::-1]
print final_map
print final_map[- 1 - 2: -2]

[9 8 7 6 5 4 3 2 1 0]
[2]


In [14]:
pq_gate = p.actions[4][1]
print type(pq_gate)
print isinstance(pq_gate, Gate)
print isinstance(pq_gate, Instr)

<class 'pyquil.quilbase.Instr'>
False
True


In [15]:
b = not 0
print b

True


In [77]:
help(p)

Help on Program in module pyquil.quil object:

class Program(pyquil.quilbase.InstructionGroup)
 |  Method resolution order:
 |      Program
 |      pyquil.quilbase.InstructionGroup
 |      pyquil.quilbase.QuilAction
 |      __builtin__.object
 |  
 |  Methods defined here:
 |  
 |  __add__(self, other)
 |      Concatenate two programs together, returning a new one.
 |      
 |      :param Program other: Another program or instruction to concatenate to this one.
 |      :return: A newly concatenated program.
 |      :rtype: Program
 |  
 |  __getitem__(self, index)
 |      Allows indexing into the program to get an action.
 |      :param index: The action at the specified index.
 |      :return:
 |  
 |  __init__(self, *instructions)
 |  
 |  __iter__(self)
 |      Allow built in iteration through a program's actions, e.g. [a for a in Program(X(0))]
 |      :return:
 |  
 |  defgate(self, name, matrix)
 |      Define a new static gate.
 |      
 |      :param string name: The name of th

In [76]:
print p.defined_gates[0].name
print p.defined_gates[0].matrix
print p.defined_gates[0].num_args()

HAD
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
1


In [64]:
for index, gate_obj in enumerate(p.actions):
    print gate_obj
    
help(p.actions[4][1])

(0, <Gate: H 0>)
(0, <Gate: H 1>)
(0, <Gate: H 2>)
(0, <Gate: H 5>)
(0, <pyquil.quilbase.Instr object at 0x7f84ed1f8050>)
Help on Instr in module pyquil.quilbase object:

class Instr(AbstractInstruction)
 |  Representation of an instruction represented by an operator, parameters, and arguments.
 |  
 |  Method resolution order:
 |      Instr
 |      AbstractInstruction
 |      QuilAction
 |      __builtin__.object
 |  
 |  Methods defined here:
 |  
 |  __eq__(self, other)
 |  
 |  __hash__(self)
 |  
 |  __init__(self, op, params, args)
 |  
 |  __str__(self)
 |  
 |  make_qubits_known(self, rm)
 |      Make the qubits involved with this instruction known to a ResourceManager.
 |      
 |      :param ResourceManager rm: A ResourceManager object.
 |  
 |  out(self)
 |  
 |  qubits(self)
 |      The qubits this instruction affects.
 |      
 |      :return: Set of qubit indexes.
 |      :rtype: set
 |  
 |  synthesize(self, resource_manager=None)
 |  
 |  -------------------------------

In [52]:
map(lambda x: x._index, p.actions[0][1].arguments)

[0]

In [59]:
print p.actions[4][1].operator_name
print p.actions[4][1].parameters
print p.actions[4][1].arguments

HAD
[]
[2]


In [53]:
print p.defined_gates[0].name
print p.defined_gates[0].matrix

HAD
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


In [56]:
p.defined_gates[0].name

'HAD'

In [88]:
p = Program()
p.inst("AND 0 0 0")

In [78]:
max_index = 0
for instruction_index, gate in p.actions:
    print gate

AND 0 0 0


In [74]:
max_index = 0
for instruction_index, gate in p.actions:
    if not isinstance(gate, Measurement):
        if max(map(lambda x: x._index, gate.arguments)) > max_index:
            max_index = max(map(lambda x: x._index, gate.arguments))

AttributeError: 'RawInstr' object has no attribute 'arguments'

In [ ]:
max_index = 0
for instruction_index, gate in program.actions:
    if not isinstance(gate, Measurement):
        if max(map(lambda x: x._index, gate.arguments)) > max_index:
            max_index = max(map(lambda x: x._index, gate.arguments))
return max_index + 1

<class 'pyquil.quilbase.Instr'>
<class 'pyquil.quilbase.Gate'>
<class 'pyquil.quilbase.Measurement'>
<class 'pyquil.quilbase.Wait'>


In [18]:
from pyquil.quilbase import Measurement
for instruction_index, gate in delocalized_fermions.actions:
    if not isinstance(gate, Measurement):
        print("hi")

hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi


In [ ]:


# the resulting state should have delocalized fermions
# psi = \sum_{i \in [1, 4], j \in [5, 8]}a_{i}^{\dagger}a_{j}^{\dagger}|0\rangle

# example execution with referenceqvm
from referenceqvm.reference import Connection
from pyquil.wavefunction import Wavefunction
rqvm = Connection(type='wavefunction')
wf, _ = rqvm.wavefunction(delocalized_fermions)
wf = Wavefunction(wf)
print wf

## Are matrices truly sparse?

In [1]:
import numpy as np
import scipy.sparse as sps
from unitary_generator import *
from gates import gate_matrix, utility_gates

In [2]:
lifted_gate(3, gate_matrix['H'], 10).todia()

<1024x1024 sparse matrix of type '<type 'numpy.complex128'>'
	with 3056 stored elements (3 diagonals) in DIAgonal format>

## Unitary Generator - Storage Requirements

In [6]:
Nq = 20
Hs = 2 ** Nq
Ps = 20
wf = np.ones((Hs, 1)).astype(np.complex128)
print("Nq = {}, number of MB: {}".format(Nq, wf.nbytes / (1024 ** 2)))

Nq = 20, number of MB: 16


In [14]:
gate_matrix['X'].shape[0] is not gate_matrix['X'].shape[1]

False

In [21]:
matrix = lifted_gate(0, gate_matrix['X'], 10)

instructions = sps.dia_matrix(matrix).astype(np.complex128)
a = instructions
size = (a.data.nbytes + a.offsets.nbytes) / (1024 ** 2)
print("Sparse storage takes: {} MB" .format(size))

instructions = matrix.toarray()
a = instructions
size = (a.nbytes) / (1024 ** 2)
print("Dense storage takes: {} MB" .format(size))

Sparse storage takes: 0 MB
Dense storage takes: 16 MB


## Unitary Gen - local SWAPs?

In [7]:
def perm_swap(*args):
    print args

perm_swap((2, 3, 4, 20))

((2, 3, 4, 20),)


In [7]:
def swap_inds_helper(i, j, arr):
    tmp = arr[i]
    arr[i] = arr[j]
    arr[j] = tmp
    
def two_swap_inds_left(j, k, ind_arr):
    """
    Mimicks the operation of two_swap_helper
    Swaps j -> k, with j always to the left (greater index) than k
    
    BREAKS LEFT ORDERING
    """
    new_arr = np.copy(ind_arr)
    if j == k:
        return new_arr
    elif j > k:
        swap_inds_helper(k - 1, k, new_arr)
        for i in xrange(j, k, -1):
            swap_inds_helper(i - 1, i, new_arr)
    elif j < k:
        for i in xrange(j, k, 1):
            swap_inds_helper(i, i + 1, new_arr)
    
    return new_arr


def two_swap_inds_right(j, k, ind_arr):
    """
    Mimicks the operation of two_swap_helper
    Swaps j -> k, with j always to the right (lower index) than k
    
    BREAKS RIGHT ORDERING
    """
    new_arr = np.copy(ind_arr)
    if j == k:
        return new_arr
    elif j > k:
        for i in xrange(j, k, -1):
            swap_inds_helper(i - 1, i, new_arr)
    elif j < k:
        swap_inds_helper(k, k + 1, new_arr)
        for i in xrange(j, k - 1, 1):
            swap_inds_helper(i, i + 1, new_arr)
    
    return new_arr

In [342]:
print "swap {} with {}".format(5 - 1, 5)
for i in range(10, 5, -1):
    print "swap {} with {}".format(i - 1, i)
print "j at 5, k at 4"

swap 4 with 5
swap 9 with 10
swap 8 with 9
swap 7 with 8
swap 6 with 7
swap 5 with 6
j at 5, k at 4


In [343]:
for i in range(5, 10):
    print "swap {} with {}".format(i, i + 1)
print "j at 10, k at 9"

swap 5 with 6
swap 6 with 7
swap 7 with 8
swap 8 with 9
swap 9 with 10
j at 10, k at 9


In [344]:
for i in range(10, 5, -1):
    print "swap {} with {}".format(i - 1, i)
print "j at 5, k at 6"

swap 9 with 10
swap 8 with 9
swap 7 with 8
swap 6 with 7
swap 5 with 6
j at 5, k at 6


In [345]:
print "swap {} with {}".format(10, 11)
for i in range(5, 10, 1):
    print "swap {} with {}".format(i, i + 1)
print "j at 10, k at 11"

swap 10 with 11
swap 5 with 6
swap 6 with 7
swap 7 with 8
swap 8 with 9
swap 9 with 10
j at 10, k at 11


In [353]:
# setup qubit index array to keep track
num_qubits = 20
qubit_arr = np.arange(num_qubits)

inds = np.array((17, 19, 13, 1, 2, 3))

# First, sort the list and find the median.
sort_i = np.argsort(inds)
sorted_inds = inds[sort_i]
med_i = int(len(sort_i) / 2)
med = sorted_inds[med_i]

# The starting position of all specified Hilbert spaces begins at 
# the qubit at (median - med_i)
start = med - med_i
# Array of final indices the arguments are mapped to, from 
# high index to low index (left to right) ordering
final_map = np.arange(start, start + len(inds))

print("We would like to map the qubit indices here:")
print(inds)
print("to the qubit indices here, preserving the above ordering:")
print(final_map)

print "We begin..."

print 

qubit_arr = two_swap_inds_left(np.where(qubit_arr == 3)[0][0], 15, qubit_arr)
print qubit_arr[final_map[0]:final_map[-1] + 1]
print 'still correct\n'

qubit_arr = two_swap_inds_left(np.where(qubit_arr == 2)[0][0], 14, qubit_arr)
print qubit_arr[final_map[0]:final_map[-1] + 1]
print 'still correct\n'

qubit_arr = two_swap_inds_left(np.where(qubit_arr == 1)[0][0], 13, qubit_arr)
print qubit_arr[final_map[0]:final_map[-1] + 1]
print 'still correct\n'

qubit_arr = two_swap_inds_left(np.where(qubit_arr == 13)[0][0], 12, qubit_arr)
print qubit_arr[final_map[0]:final_map[-1] + 1]
print 'still correct\n'

qubit_arr = two_swap_inds_left(np.where(qubit_arr == 19)[0][0], 11, qubit_arr)
print qubit_arr[final_map[0]:final_map[-1] + 1]
print 'incorrect now!\n'

qubit_arr = two_swap_inds_left(np.where(qubit_arr == 17)[0][0], 10, qubit_arr)
print qubit_arr[final_map[0]:final_map[-1] + 1]
print 'incorrect now!\n'

print "let's look at more of the array:"
print qubit_arr
print "one more loop through, but backwards"

qubit_arr = two_swap_inds_right(np.where(qubit_arr == 17)[0][0], 10, qubit_arr)
print qubit_arr[final_map[0]:final_map[-1] + 1]

qubit_arr = two_swap_inds_right(np.where(qubit_arr == 19)[0][0], 11, qubit_arr)
print qubit_arr[final_map[0]:final_map[-1] + 1]

qubit_arr = two_swap_inds_right(np.where(qubit_arr == 13)[0][0], 12, qubit_arr)
print qubit_arr[final_map[0]:final_map[-1] + 1]

qubit_arr = two_swap_inds_right(np.where(qubit_arr == 1)[0][0], 13, qubit_arr)
print qubit_arr[final_map[0]:final_map[-1] + 1]

qubit_arr = two_swap_inds_right(np.where(qubit_arr == 2)[0][0], 14, qubit_arr)
print qubit_arr[final_map[0]:final_map[-1] + 1]

qubit_arr = two_swap_inds_right(np.where(qubit_arr == 3)[0][0], 15, qubit_arr)
print qubit_arr[final_map[0]:final_map[-1] + 1]

# print 'incorrect now!\n'

# qubit_arr = two_swap_inds(1, 13, qubit_arr)
# print qubit_arr[final_map[0]:final_map[-1] + 1]
# qubit_arr = two_swap_inds(1, 13, qubit_arr)
# print qubit_arr[final_map[0]:final_map[-1] + 1]

# qubit_arr = two_swap_inds(10, 19, qubit_arr)
# print qubit_arr

We would like to map the qubit indices here:
[17 19 13  1  2  3]
to the qubit indices here, preserving the above ordering:
[10 11 12 13 14 15]
We begin...

[11 12 13 14 15  3]
still correct

[12 13 14 15  2  3]
still correct

[13 14 15  1  2  3]
still correct

[14 15 13  1  2  3]
still correct

[15 19 14 13  1  2]
incorrect now!

[17 12 19 14 13  1]
incorrect now!

let's look at more of the array:
[ 0  4  5  6  7  8  9 10 11 15 17 12 19 14 13  1  2  3 16 18]
one more loop through, but backwards
[17 12 19 14 13  1]
[17 19 12 14 13  1]
[17 19 13 12 14  1]
[17 19 13  1 12 14]
[17 19 13  1  2 12]
[17 19 13  1  2  3]


In [12]:
# setup qubit index array to keep track
num_qubits = 20
qubit_arr = np.arange(num_qubits)

x = np.arange(num_qubits)
np.random.shuffle(x)
x = np.array([15, 16, 18, 2, 10])

inds = x

# First, sort the list and find the median.
sort_i = np.argsort(inds)
sorted_inds = inds[sort_i]
med_i = int(len(sort_i) / 2)
med = sorted_inds[med_i]

# The starting position of all specified Hilbert spaces begins at 
# the qubit at (median - med_i)
start = med - med_i
# Array of final indices the arguments are mapped to, from 
# high index to low index (left to right) ordering
final_map = np.arange(start, start + len(inds))

print("We would like to map the qubit indices here:")
print(inds)
print("to the qubit indices here, preserving the above ordering:")
print(final_map)

print "We begin..."

print 

def iter_swap(source_num, dest_ind, arr, vec='left'):
    source_ind = np.where(arr == source_num)[0][0]
    if vec == 'left':
        res = two_swap_inds_left(source_ind, dest_ind, arr)
    else:
        res = two_swap_inds_right(source_ind, dest_ind, arr)
    print arr[final_map[0]:final_map[-1] + 1]
    return arr

print qubit_arr[final_map[0]:final_map[-1] + 1]

# left iter
for i in range(len(final_map))[::-1]:
    qubit_arr = two_swap_inds_left(np.where(qubit_arr == inds[i])[0][0], final_map[i], qubit_arr)
    print qubit_arr[final_map[0]:final_map[-1] + 1]
    if np.allclose(qubit_arr[final_map[0]:final_map[-1] + 1], x):
        print "reached!"
        break
    
# right iter
for i in range(len(final_map)):
    if not np.allclose(qubit_arr[final_map[0]:final_map[-1] + 1], x):
        print "needed second iteration..."
    else:
        break
    qubit_arr = two_swap_inds_right(np.where(qubit_arr == inds[i])[0][0], final_map[i], qubit_arr)
    print qubit_arr[final_map[0]:final_map[-1] + 1]


# qubit_arr = iter_swap(7, 14, qubit_arr, vec='left')

We would like to map the qubit indices here:
[15 16 18  2 10]
to the qubit indices here, preserving the above ordering:
[13 14 15 16 17]
We begin...

[13 14 15 16 17]
[14 15 16 17 10]
[15 16 17  2 10]
[15 17 18 16  2]
[17 16 15 18  2]
[15 14 16 18  2]
needed second iteration...
[15 14 16 18  2]
needed second iteration...
[15 16 14 18  2]
needed second iteration...
[15 16 18 14  2]
needed second iteration...
[15 16 18  2 14]
needed second iteration...
[15 16 18  2 10]


In [281]:
num_qubits = 20
qubit_arr = np.arange(num_qubits)
print qubit_arr
swap_inds(10, 19, qubit_arr)
print qubit_arr

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 19 11 12 13 14 15 16 17 18 10]


# Unitary Gen - generalized SWAP

In [123]:
j = 10
k = 5

bin(1 << j)

'0b10000000000'

In [154]:
x = 1 << 2
y = 1 << 4
ans = 237

res1 = ans & x is 0 
res2 = ans & y is 0 
print res1 ^ res2

True


In [169]:
def mask_swap(j, k, state_list):
    j_mask = 1 << j
    k_mask = 1 << k
    print j, k
    return map(lambda state: (state & j_mask >> j) ^ (state & k_mask >> k), state_list)

In [170]:
states = range(20)
for i in states:
    print i & (1 << 2) >> 2

0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1


In [273]:
def decompose_states(j, k, states):
    num_qubits = np.log2(states.shape[0]).astype(int)

    assert j < k or j > k
    assert j <= num_qubits - 1 and j >= 0
    assert k <= num_qubits - 1 and k >= 0

    # Compute the other bits, by excising the left/right SWAP bits
    low_num = j
    mid_num = k - low_num - 1
    high_num = num_qubits - low_num - mid_num - 2
    
    low_mask = np.left_shift(np.ones(states.shape[0]).astype(np.int64), low_num) - 1
    mid_mask = np.left_shift(np.ones(states.shape[0]).astype(np.int64), mid_num) - 1
    mid_mask = np.left_shift(mid_mask, low_num + 1)
    high_mask = np.left_shift(np.ones(states.shape[0]).astype(np.int64), high_num) - 1
    high_mask = np.left_shift(high_mask, low_num + mid_num + 2)
    
    high_part = np.right_shift(np.bitwise_and(states, high_mask), 2)
    mid_part = np.right_shift(np.bitwise_and(states, mid_mask), 1)
    low_part = np.bitwise_and(states, low_mask)

    other_bits = low_part + mid_part + high_part
    
    # Compute the left and right bits in arrays
    
    j_mask = np.left_shift(np.ones(states.shape[0]).astype(np.int64), j)
    k_mask = np.left_shift(np.ones(states.shape[0]).astype(np.int64), k)
    
    left_bits = np.right_shift(np.bitwise_and(states, j_mask), j)
    right_bits = np.right_shift(np.bitwise_and(states, k_mask), k)
    
    return other_bits, left_bits, right_bits

In [274]:
states = np.arange(2 ** 4).astype(np.int64)
ob, lb, rb = decompose_states(0, 1, states)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 1 1 1 2 2 2 2 3 3 3 3]


In [ ]:
def construct_SWAP(ob, lb, rb, num_qubits):
    swapped_states = np.bitwise_xor(lb, rb)
    ob = pd.factorize(ob)
    
    for ind in ob[1]:
        new_range = np.where(ob[0] == ind)[0]
        

In [264]:
import pandas as pd
print ob
print np.bitwise_xor(lb, rb)
ob = pd.factorize(ob)
swapped_states = np.bitwise_xor(lb, rb)

[0 0 0 0 1 1 1 1]
[0 1 1 0 0 1 1 0]


In [254]:
ob

(array([0, 0, 0, 0, 1, 1, 1, 1]), array([0, 1]))

In [267]:
zip(ob[0], swapped_states)

[(0, 0), (0, 1), (0, 1), (0, 0), (1, 0), (1, 1), (1, 1), (1, 0)]

In [268]:
print ob[0]
print swapped_states

[0 0 0 0 1 1 1 1]
[0 1 1 0 0 1 1 0]


In [272]:
for ind in ob[1]:
    print [i if swap == 1 for (sid, swap) in zip(ob[0], swapped_states)]

SyntaxError: invalid syntax (<ipython-input-272-e035fcbe199d>, line 2)

In [195]:
j = 0
k = 1

states = np.arange(2 ** 3).astype(int)
j_mask = np.left_shift(np.ones(states.shape[0]).astype(np.int64), j)
k_mask = np.left_shift(np.ones(states.shape[0]).astype(np.int64), k)

oth_bits = None

left_bits = np.right_shift(np.bitwise_and(states, j_mask), j)
right_bits = np.right_shift(np.bitwise_and(states, k_mask), k)

print left_bits
print right_bits

print np.bitwise_xor(left_bits, right_bits)

[0 1 0 1 0 1 0 1]
[0 0 1 1 0 0 1 1]
[0 1 1 0 0 1 1 0]


In [232]:
j = 3
k = 5
num_qubits = 10

# print bin(1 << j)
# print bin((1 << j) - 1)
# print bin(1 << k)
# print bin((1 << k) - 1)

low_num = j
mid_num = k - low_num - 1
high_num = num_qubits - low_num - mid_num - 2

low_mask = (1 << low_num) - 1
mid_mask = ((1 << mid_num) - 1) << (low_num + 1)
high_mask = ((1 << high_num) - 1) << (low_num + mid_num + 2)

# print bin(low_mask)
# print bin(mid_mask)
# print bin(high_mask)

num = 756
print "{} in binary is:".format(num)
print bin(num)

high_part = (num & high_mask) >> 2
mid_part = (num & mid_mask) >> 1
low_part = (num & low_mask)

print "High, mid, and low parts:"
print bin(high_part)
print bin(mid_part)
print bin(low_part)
print bin(low_part + mid_part + high_part)

756 in binary is:
0b1011110100
High, mid, and low parts:
0b10110000
0b1000
0b100
0b10111100


In [119]:
for i in range(1, 9, 1):
    x = bin(i)
    y =
    print x

0b1
0b10
0b11
0b100
0b101
0b110
0b111
0b1000
